### ISSUE TITLE
Cannot read property 'current' of undefined. 

### ISSUE THREAD

**Issue by Thuan2000** [FormidableLabs/react-ssr-prepass#7]
Here is the error: 

`TypeError: Cannot read property 'current' of undefined
    at Object.<anonymous> (/home/thuan/Desktop/thotot/main/node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js:842:45)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/thuan/Desktop/thotot/main/node_modules/react-ssr-prepass/index.js:4:20)
    at Module._compile (module.js:652:30)`

**Comment by kc-cloud** [comment]
I'm having the same issue.

**Comment by blaineo** [comment]
Same!

**Comment by macdougall** [comment]
Is there any response to this? I'm getting the exame issue above.

TypeError: Cannot read property 'current' of undefined at Object.<anonymous>

**Comment by cia700** [comment]
I am having the same issue, any update on this ? 

thanks

**Comment by sayuti-daniel** [comment]
React and React DOM must be at least `16.8.0` https://github.com/FormidableLabs/react-ssr-prepass/pull/5

**Comment by kitten** [comment]
Sorry for the late reply. As indicated in the last comment, react must at least be at `16.8` https://github.com/FormidableLabs/react-ssr-prepass/blob/master/package.json#L60-L61
